/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'

const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/registry': typeof RegistryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/registry': typeof RegistryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/playground': typeof PlaygroundRoute
  '/registry': typeof RegistryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logs' | '/playground' | '/registry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logs' | '/playground' | '/registry'
  id: '__root__' | '/' | '/logs' | '/playground' | '/registry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RegistryRoute: typeof RegistryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  PlaygroundRoute: PlaygroundRoute,
  RegistryRoute: RegistryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
